"""empty message

Revision ID: cbeca08a4c90
Revises: dd27492a3a1a
Create Date: 2021-09-09 16:10:04.823744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbeca08a4c90'
down_revision = 'dd27492a3a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('classes_user_id_fkey', 'classes', type_='foreignkey')
    op.drop_column('classes', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('classes_user_id_fkey', 'classes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
